import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "primary": "#000000",
                "on-primary": "#ffffff",
                "primary-container": "#131b2e",
                "on-primary-container": "#7c839b",
                "primary-fixed": "#dae2fd",
                "primary-fixed-dim": "#bec6e0",
                "on-primary-fixed": "#131b2e",
                "on-primary-fixed-variant": "#3f465c",
                "secondary": "#855300",
                "on-secondary": "#ffffff",
                "secondary-container": "#fea619",
                "on-secondary-container": "#684000",
                "secondary-fixed": "#ffddb8",
                "secondary-fixed-dim": "#ffb95f",
                "on-secondary-fixed": "#2a1700",
                "on-secondary-fixed-variant": "#653e00",
                "tertiary": "#000000",
                "on-tertiary": "#ffffff",
                "tertiary-container": "#271901",
                "on-tertiary-container": "#98805d",
                "tertiary-fixed": "#fcdeb5",
                "tertiary-fixed-dim": "#dec29a",
                "on-tertiary-fixed": "#271901",
                "on-tertiary-fixed-variant": "#574425",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#93000a",
                "background": "#faf8ff",
                "on-background": "#131b2e",
                "surface": "#faf8ff",
                "on-surface": "#131b2e",
                "surface-variant": "#dae2fd",
                "on-surface-variant": "#45464d",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f2f3ff",
                "surface-container": "#eaedff",
                "surface-container-high": "#e2e7ff",
                "surface-container-highest": "#dae2fd",
                "surface-bright": "#faf8ff",
                "surface-dim": "#d2d9f4",
                "surface-tint": "#565e74",
                "outline": "#76777d",
                "outline-variant": "#c6c6cd",
                "inverse-surface": "#283044",
                "inverse-on-surface": "#eef0ff",
                "inverse-primary": "#bec6e0",
            },
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                headline: ['Manrope', ...defaultTheme.fontFamily.sans],
                body: ['Inter', ...defaultTheme.fontFamily.sans],
                label: ['Inter', ...defaultTheme.fontFamily.sans],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '9999px',
            },
        },
    },

    plugins: [forms],
};
